### ISSUE TITLE
[BUG] Cluster reports as offline always with k3d

### ISSUE THREAD

**Issue by KyleSanderson** [cnrancher/autok3s#436] opened 2022-05-05 04:03 UTC
**Describe the bug**
Unable to kube-explore or anything with autok3s. There doesn't seem to be any way to resolve this. 3 masters, 1 worker. 1 master and no workers also throws an error.

**To reproduce**
1. Create a cluster
2. Refresh the page
3. Cluster is reported as offline - containers and everything work.

**Expected behavior**
The webpage works.

**Screenshots**

**Environments (please complete the following information):**
 - OS: Unraid
 - AutoK3s Version: latest.

**Additional context**

**Comment by JacieChao** [comment] 2022-05-05 08:27
@KyleSanderson Thanks for your issue! 
Could you please provide more information about the issue?
1. Which command are you using to start AutoK3s server? Are you running AutoK3s with the docker or using binary?
2. Could you provide your K3d provider configuration about this issue? no matter UI screenshot or CLI command?

**Comment by KyleSanderson** [comment] 2022-05-05 23:02
> @KyleSanderson Thanks for your issue! Could you please provide more information about the issue?
> 
> 1. Which command are you using to start AutoK3s server? Are you running AutoK3s with the docker or using binary?
> 2. Could you provide your K3d provider configuration about this issue? no matter UI screenshot or CLI command?

Are you able to provide evidence this works? no matter the configuration attempted it fails with k3d.

**Comment by JacieChao** [comment] 2022-05-07 02:16
> 
> Are you able to provide evidence this works? no matter the configuration attempted it fails with k3d.

I can create cluster using K3d provider using the following command
```
autok3s create --provider k3d --master 1 --worker 1 --api-port 0.0.0.0:0 --image rancher/k3s:v1.21.7-k3s1
```

The cluster works fine and I can also enable kube-explorer from UI and access to kube-explorer dashborad
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/23305062/167233930-efbcbcf3-646d-4131-b1d8-b8cbb11d8a5b.png">

I think it would be more helpful if you could provide some reproduce steps and error logs when running AutoK3s.

**Comment by orangedeng** [comment] 2022-08-29 06:48
Going to close this issue because it is not active for long. Feel free to reopen this issue if there are more informations.

**Closed by orangedeng** 2022-08-29 06:48 UTC
Labels: bug
